services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379' 
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - my-vol:/code
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
volumes:
  my-vol: